---
- name: Install .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_facts["env"]["HOME"] }}/.zshrc"
    backup: true
    mode: "0644"

- name: Install .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: "{{ ansible_facts["env"]["HOME"] }}/.zprofile"
    backup: true
    mode: "0644"
