---
- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ ansible_facts["env"]["HOME"] }}/.config"
    state: directory
    mode: "0755"

- name: Install starship.toml
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ ansible_facts["env"]["HOME"] }}/.config/starship.toml"
    backup: true
    mode: "0644"
